name: tagged_text_span
description: A package that map tags in a given text appling a custom span configuration to it.
version: 1.0.0
homepage: 

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
